# This file defines a GitHub Actions workflow for a CI/CD pipeline for the Autoencoder ML project
name: CI/CD Workflow for Autoencoder

# Trigger workflow on specific events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs in the workflow
jobs:
  lint:
    name: Lint Code
    runs-on: windows-latest  # Use Windows environment

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run linter
        run: |
          flake8 Autoencoder.py --count --select=E9,F63,F7,F82 --show-source --statistics

  test:
    name: Run Tests
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install keras numpy matplotlib

      - name: Test script execution
        run: |
          python Autoencoder.py

  deploy:
    name: Deploy Model
    runs-on: windows-latest
    needs: [lint, test]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Deploy to mock environment
        run: |
          echo "Simulating deployment of the autoencoder model."
